# xAuth by xFlare config file.

#------------[Authenticatin Settings]------------#
# Type of authentication?
# Options: YML & MYSQL.
# MYSQL not implemented
autentication-type: YML

# If MYSQL enabled, provide details here. No one will be able to see it.
username: ""
password: ""
port: 3306
server: ""

# Authenticate players with there IP address?
ip-auth: false

# How many characters must a password be?
max-characters: 10
shortest-characters: 6

# Use aysnc task to login? (Huge performamce boost, but may cause a half a sec tick delay when reciveing password)
# Only for MySQL
use-async: false

# Enable database checks? (Recomended, checks every couple of ticks to make sure the database is onlie, errors, etc)
# Only for MySQL
database-checks: false

# Send users a message below the hot bar? Ex: "Please login to play!"
hotbar-message: true

# Enable password changing? Will enable /changepw
# Not implemented
enable-pass-changing: true

# Block simple passwords? Prevents players from easily guessing players passwords!
# Blocks passwords that don't have numbers or are easy like: "987654321", "asdf", ect.
simple-passcode-blocker: false

# Require email? Will force players to use an email to register.
# Not implemented
require-email: false

# Kick players after how many seconds of not being authenticated?
enable-kick: false
kick-after-seconds: 120

# Kick players after X amount of invalid login attempts?
enable-kick-invalid: false
kick-after-invailds: 3

# Max numbers of registered accounts allowed per IP?
# Set to false if you want to allow unlimited accounts.
# Not implemented.
max-accounts: 5

# Delete old accounts that have not been used for a while?
# Not implemented.
delete-old-accounts: false

# Hash Options:
# Passwords will always be hashed.
# Not implemented
hash-ips: false
hash-usernames: false

# Check if YML is currpted when players leave the game?
check-yml: true

#------------[Authenticatin Settings]------------#


#------------[Auth Events]------------#
# What to allow/disallow when not authenticated?
allow-movement: false
allow-commands: false
allow-block-placing: false
allow-block-breaking: false
allow-shoot-arrows: false
allow-drops: false
allow-item-pickup: false
allow-pvp: false
allow-damage: false
#------------[Auth Events]------------#


#------------[General]------------#
# Anounce player join? xAuth let's you choose whether you want "player has joined the server".
player-join: false

# Anounce player quit? xAuth let's you choose whether you want "player has left the server".
player-quit: false

# Show there auth status when not logged in? Username: "[Not-Logged-In] Steve"
show-username-auth-status: true
#------------[General]------------#

#----------------[Messages]----------------#
# Messages sent throughout the plugin, they are gray by default.
# Use a line break to split chat messages. Use: \n
# Add a splash of color with color symbols! Use: ยง<letter/number>
join: "Welcome to my server!"
login: "Please log-in to play."
registered: "You are now registered."
already-registered: "This username is already registered."
unregister: "You are now unregistered."
disable: "xAuth is disabled at this moment."
logged: "You are now logged in."
incorrect: "Incorrect password."
error: "An error has occured."
success: "Thanks! Please retype the password to make sure you did not make a mistake."
no-success: "That password did not match the first one! Please type a new wanted password."
short: "That password was too short!"
long: "That password was too long!"
please-register: "Please regster this account to play!"
wanted: "Type your wanted password in chat."
sharing: "Do not share your password!"
ipauthed: "You have been ip-authed."

# Hotbar messages if enabled.
hotbar-login: "Please login to play!"
hotbar-register: "Please register to play!"
hotbar-disabled: "xAuth is currently disabled!"

# If simple-passcode-blocker enabled, here are the langs:
simple: "That password was too simple! Please add numbers and make it more unique."

# If brute-force messages if enabled.
kick: "You tried too login to many times!"

# Timout messages if enabled.
timeout: "You been un-authenticated for too long!"
#----------------[Messages]----------------#

# Safe mode, if xAuth is not enabled due to some sort of error, don't let players do anything?
# Protects you against bad plugins that try to use the API for bad reasons.
safe-mode: true

# API allows other plugins to access xAuth's data with ease, enabling it will register the API class.
# Safe-Mode is best with this option.
enable-api: true

# Debug-mode? (Notice: You can't turn this off on beta releases)
debug-mode: true

# Creates a log file and logs console outputs. You cannot turn this off with debug.
log-xauth: true

# Auto-Update xAuth? This is very useful for getting the latest patches instantly!
# Not implemented
auto-update-xauth: true

#-------- Danger Zone! --------#
# Dangerous experimental setting that should not be edited!

# Change tick rate. 
tick-rate: 20

# Don't close session? May cause memory leaks!
close-session: true

# When to dump logger? Less memory usage if the number is lower. Can't be lower then 1!
dump-logger: 1

# For internal use only. Do NOT edit.
version: "1.0.0 beta 5"
