# xAuth by xFlare config file.
# Some options may not work properly yet!

#------------[Authenticatin Settings]------------#
# Type of authentication?
# YML or MySQL?
autentication-type: YML

# Authenticate players with there IP address?
ip-auth: false

# Use aysnc task to login? (Huge performamce boost, but may cause a half a sec tick delay when reciveing password)
# Only for MySQL
use-async: false

# Enable database checks? (Recomended, checks every couple of ticks to make sure the database is onlie, errors, ect)
# Only for MySQL
database-checks: false

# Send users a message below the hot bar letting them know what to do? (Recommend you keep this on)
hotbar-message: true

# Enable password changing?
enable-pass-changing: true

# Block simple passwords?
simple-passcode-blocker: true

# Require email? Will force players to use an email to register.
require-email: false

# Kick players after how many seconds of not being authenticated?
# Not implemented yet.
enable-kick: false
kick-after-seconds: 120

# Kick players after X amount of invalid login attempts?
# Not implemented yet. 
enable-kick-invalid: false
kick-after-invailds: 3

#------------[Authenticatin Settings]------------#


#------------[Auth Events]------------#
# What to allow/disallow when not authenticated?
allow-movement: false
allow-commands: false
allow-block-placing: false
allow-block-breaking: false
#------------[Auth Events]------------#


#------------[General]------------#
# Anounce player join? xAuth let's you choose whether you want "player has joined the server".
player-join: false

# Anounce player quit? xAuth let's you choose whether you want "player has left the server".
player-quit: false

# Show there auth status when not logged in? Username: "[Not-Logged-In] Steve"
show-username-auth-status: true
#------------[General]------------#

#----------------[Messages]----------------#
# Messages sent throughout the plugin.
join: "Welcome to the server!"
login: "Please log-in to play."
registered: "You are now registered"
already-registered: "This username is already registered."
disable: "xAuth is disabled at this moment."
logged: "You are now logged in"
incorrect: "Incorrect password"
error: "An error has occured"
#----------------[Messages]----------------#

# Safe mode, if xAuth is not enabled due to some sort of error, don't let players do anything?
# Protects you against bad plugins that try to use the API for bad reasons.
safe-mode: true

# API allows other plugins to access xAuth's data with ease, enabling it will register the API class.
# Safe-Mode is best with this option.
enable-api: true

# Debug-mode? (Notice: You can't turn this off on beta releases)
debug-mode: true

# Creates a log file and logs things. You cannot turn this off with debug.
log-xauth: true

# Auto-Update xAuth? This is very useful for getting the latest patches instantly!
# Not implemented
auto-update-xauth: true

# For internal use only. Do NOT edit.
version: 1.0.0
